export const adminRouter = {
  ADMIN_LOGIN: 'admin-login',
  ADMIN_USER: 'admin-user',
  ADMIN_POST: 'admin-post',
  ADMIN_NEWS: 'admin-news',
  ADMIN_ACCOUNT: 'admin-account',
  ADMIN_CATEGORIES: 'admin-categories',
  ADMIN_POST_DETAIL: 'admin-post-detail',
  ADMIN_NEWS_CREATE: 'admin-news-create',
  ADMIN_NEWS_EDIT: 'admin-news-edit',
  ADMIN_PARTNER: 'admin-partner',
  ADMIN_PARTNER_CREATE: 'admin-partner-create',
  ADMIN_PARTNER_EDIT: 'admin-partner-edit',
  ADMIN_SERVICE: 'admin-service',
  ADMIN_SERVICE_CREATE: 'admin-service-create',
  ADMIN_SERVICE_EDIT: 'admin-service-edit',
  ADMIN_INTRODUCE: 'admin-introduce',
  ADMIN_INTRODUCE_CREATE: 'admin-introduce-create',
  ADMIN_INTRODUCE_EDIT: 'admin-introduce-edit',
  ADMIN_REPORT: 'admin-report',
  ADMIN_REPORT_CREATE: 'admin-report-create',
  ADMIN_REPORT_VIEW: 'admin-report-view',
  ADMIN_REPORT_EDIT: 'admin-report-edit',
  ADMIN_RECRUITMENT:'admin-recruitment',
  ADMIN_RECRUITMENT_CREATE:'admin-recruitment-create',
  ADMIN_RECRUITMENT_EDIT:'admin-recruitment-edit'
}
